
infoFormat: 0 # Формат вывода информации. 0 или 1

botsCount: 100 # Сколько ботов должно зайти на 1 сервер за раз.
joinDelay: 50 # Задержка отправки ботов на сервер (мс).

randomNicks: false # Использовать ли рандомные ники?
randomNicksLength: 8 # Длина рандомного ника.

debug: false # Включить режим разработчика

randomPasswords: false # Использовать ли рандомные пароли?
randomPasswordsLength: 9 # Длина рандомного пароля.

doubleJoin: false # Будут ли боты перезаходить 2 раз если их кикнуло?
antiBotFilter: false # Удалять ли из списка серверов сервера с BotFilter?

testMode: false # Тестовый режим, позволяет отправлять всех ботов на один сервер.
testModeIp: "127.0.0.1:25565" # Ип тестового режима.

autoRestart: false # Включить ли авто рестарт? (очень рекомендую)
autoRestartDelay: 8 # Через сколько минут произойдёт рестарт. Для наилучшей эффективности ставьте не больше 10.

move: false # Будут ли боты ходить?

enable-duration: false # Включить ли длительность работы?
duration: 380 # Длительность работы. (секунды)

nofiles: true

commands: # Что бот будет писать в чат. У wait есть только s (секунды), ms (миллисекунды)
  - 'wait 1s'
  - "/register 123123 123123"
  - "!Крамекс Лучший Кто не Согласен Пусть Сосёт BIG CHLEN vk.com/kramecse"
  - "/me!Крамекс Лучший Кто не Согласен Пусть Сосёт BIG CHLEN vk.com/kramecse"
  - "/minecraft:me!Крамекс Лучший Кто не Согласен Пусть Сосёт BIG CHLEN vk.com/kramecse"
  - "!Крамекс Лучший vk.com/kramecse"
  - "!Крамекс Лучший vk.com/kramecse"